apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: test-july-27-configmap
images:
- name: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/test-july-27
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/version: ""
namePrefix: dev-
namespace: dev
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
resources:
- ../../base
